myOthersmenu = { 
{ 'SAGE' , 'urxvtc -e /opt/sage/sage -notebook' },
{ 'Anki' , 'anki' },
{ 'dosbox Emulator' , 'dosbox' },
{ 'i3' , 'i3' },
{ 'LibreOffice XSLT based filters' , 'libreoffice %U' },
}
myGamemenu = { 
{ 'The Elder Scrolls : Daggerfall' , 'dosbox /home/nicolas/Games/dosbox/dagger.bat' },
{ 'FreeCell Solitaire' , 'sol --freecell' },
{ 'VBA-M' , 'gvbam' },
{ 'Lugaru' , 'lugaru' },
{ 'Minecraft' , 'minecraft' },
{ 'Minetest' , 'minetest' },
{ 'Pokémon Version Rouge' , 'gvbam /home/nicolas/Games/Pokemon_Rouge_Pokeblog_FR/pkmn_rouge.gbc' },
{ 'AisleRiot Solitaire' , 'sol' },
{ 'TeeWorlds' , 'teeworlds' },
{ 'Xmoto' , 'xmoto' },
}
myGraphicsmenu = { 
{ 'Gcolor2' , 'gcolor2' },
{ 'GNU Image Manipulation Program' , 'gimp-2.8 %U' },
}
myAudioVideomenu = { 
{ 'Asunder CD Ripper' , 'asunder' },
{ 'Create a Video Project' , 'brasero --video' },
{ 'Me TV' , 'me-tv-client' },
{ 'MPlayer Media Player' , 'mplayer %F' },
{ 'QT V4L2 test Utility' , 'qv4l2' },
{ 'Sonata' , 'sonata' },
{ 'VLC media player' , '/usr/bin/vlc %U' },
{ 'XBMC Media Center' , 'xbmc' },
}
myOfficemenu = { 
{ 'AbiWord' , 'abiword' },
{ 'Bitcoin' , '/usr/bin/bitcoin-qt' },
{ 'ePDFViewer' , 'epdfview %f' },
{ 'Document Viewer' , 'evince %U' },
{ 'Gnumeric' , 'gnumeric %U' },
{ 'HomeBank' , 'homebank %F' },
{ 'New Spreadsheet' , 'libreoffice --calc %U' },
{ 'New Drawing' , 'libreoffice --draw %U' },
{ 'New Presentation' , 'libreoffice --impress %U' },
{ 'LibreOffice ' , 'libreoffice %U' },
{ 'New Document' , 'libreoffice --writer %U' },
{ 'Wordview Microsoft doc Viewer' , 'wordview' },
{ 'Zathura' , 'zathura %f' },
}
myUtilitymenu = { 
{ '7-Zip FM' , '7zFM' },
{ 'File Manager' , 'exo-open --launch FileManager %u' },
{ 'Terminal Emulator' , 'exo-open --launch TerminalEmulator' },
{ 'Archive Manager' , 'file-roller %U' },
{ 'Graphical Disk Map' , 'gdmap' },
{ 'Root Terminal' , 'gksu -l gnome-terminal' },
{ 'Image Viewer' , 'gpicview %f' },
{ 'Vi IMproved' , 'gvim -f %F' },
{ 'KeePassX' , 'keepassx %f' },
{ 'LilyTerm' , 'lilyterm' },
{ 'Terminology' , 'terminology' },
{ 'Xarchiver' , 'xarchiver' },
{ 'About Xfce' , 'xfce4-about' },
}
myDevelopmentmenu = { 
{ 'CMake' , 'cmake-gui %f' },
{ 'Arduino' , 'arduino' },
{ 'Qt Assistant' , '/usr/bin/assistant' },
{ 'Data Display Debugger' , 'ddd' },
{ 'Qt Designer' , '/usr/bin/designer' },
{ 'Editje' , 'editje-bin %F' },
{ 'Eeschema' , 'eeschema' },
{ 'Elementary Test' , 'elementary_test' },
{ 'FLUID' , 'fluid %F' },
{ 'OpenJDK Monitoring & Management Console' , '/usr/lib/jvm/java-6-openjdk/bin/jconsole' },
{ 'KiCad' , 'kicad' },
{ 'Qt Linguist' , '/usr/bin/linguist' },
{ 'LÖVE' , '/usr/bin/love' },
{ 'OpenJDK Policy Tool' , '/usr/lib/jvm/java-6-openjdk/bin/policytool' },
{ 'GNU Octave' , 'urxvtc -e /usr/bin/octave' },
}
myNetworkmenu = { 
{ 'Avahi SSH Server Browser' , '/usr/bin/bssh' },
{ 'Avahi VNC Server Browser' , '/usr/bin/bvnc' },
{ 'Chromium' , 'chromium %U' },
{ 'Deluge' , 'deluge-gtk %U' },
{ 'ELinks' , '/usr/bin/elinks %u' },
{ 'Mail Reader' , 'exo-open --launch MailReader %u' },
{ 'Web Browser' , 'exo-open --launch WebBrowser %u' },
{ 'Firefox' , 'firefox %u' },
{ 'Gajim' , 'gajim' },
{ 'Luakit' , 'luakit %u' },
{ 'Thunderbird' , 'thunderbird %u' },
{ 'XChat IRC' , 'xchat' },
{ 'Zenmap (as root)' , '/usr/share/zenmap/su-to-zenmap.sh %F' },
{ 'Zenmap' , 'zenmap %F' },
}
mySystemmenu = { 
{ 'Bulk Rename' , '/usr/lib/Thunar/ThunarBulkRename %F' },
{ 'Open Folder with Thunar' , 'thunar %F' },
{ 'Thunar File Manager' , 'thunar %F' },
{ 'Avahi Zeroconf Browser' , '/usr/bin/avahi-discover' },
{ 'CD/DVD Creator' , 'nautilus --no-default-window --no-desktop burn:/// ' },
{ 'dconf Editor' , 'dconf-editor' },
{ 'Enlightenment File Manager' , 'enlightenment_filemanager %U' },
{ 'EtherApe' , 'etherape' },
{ 'GParted' , 'gparted-pkexec' },
{ 'GSmartControl' , 'pkexec /usr/bin/gsmartcontrol' },
{ 'Htop' , 'urxvtc -e htop' },
{ 'UNetbootin' , '/usr/bin/unetbootin' },
{ 'urxvt (tabbed)' , 'urxvt-tabbed' },
{ 'urxvt' , 'urxvt' },
{ 'urxvt (client)' , 'urxvtc' },
{ 'UXTerm' , 'uxterm' },
{ 'Oracle VM VirtualBox' , 'VirtualBox %U' },
{ 'Wireshark' , 'wireshark %f' },
{ 'XTerm' , 'xterm' },
}
mySettingsmenu = { 
{ 'ARandR' , 'arandr' },
{ 'Manage Printing' , '/usr/bin/xdg-open http://localhost:631/' },
{ 'Elementary Configuration' , 'elementary_config' },
{ 'Preferred Applications' , 'exo-preferred-applications' },
{ 'Adobe Flash Player' , 'flash-player-properties' },
{ 'Privilege granting' , 'gksu-properties' },
{ 'Customize Look and Feel' , 'lxappearance' },
{ 'NVIDIA X Server Settings' , '/usr/bin/nvidia-settings' },
{ 'Qt Config ' , '/usr/bin/qtconfig' },
{ 'Print Settings' , 'system-config-printer' },
{ 'File Manager' , 'thunar-settings' },
{ 'Removable Drives and Media' , 'thunar-volman-settings' },
}
categoriesMenu = { 
{ 'Settings' , mySettingsmenu },
{ 'System' , mySystemmenu },
{ 'Network' , myNetworkmenu },
{ 'Development' , myDevelopmentmenu },
{ 'Utility' , myUtilitymenu },
{ 'Office' , myOfficemenu },
{ 'AudioVideo' , myAudioVideomenu },
{ 'Graphics' , myGraphicsmenu },
{ 'Game' , myGamemenu },
{ 'Others' , myOthersmenu },
{ 'Actualiser', 'lua /home/nicolas/.config/awesome/lib/menuMaker.lua'},
 }
