myOthersmenu = { 
{ 'Anki' , 'anki' },
{ 'LibreOffice XSLT based filters' , 'libreoffice %U' },
{ 'R' , 'urxvtc -e R' },
{ 'SAGE' , 'urxvtc -e /opt/sage/sage -notebook' },
{ 'Scilab' , 'scilab' },
{ 'Wine Windows Program Loader' , 'wine start /unix %f' },
}
myGamemenu = { 
{ '0 A.D.' , '/usr/bin/0ad' },
{ 'freedroidrpg' , 'freedroidRPG' },
{ 'Lugaru' , 'lugaru' },
{ 'Mana' , 'mana' },
{ 'Minecraft' , 'minecraft' },
{ 'Naev' , 'naev' },
{ 'PlayOnLinux' , 'playonlinux' },
{ 'Dungeon Crawl Stone Soup' , 'crawl-tiles' },
{ 'Warsow' , 'warsow' },
}
myGraphicsmenu = { 
{ 'GNU Image Manipulation Program' , 'gimp-2.8 %U' },
{ 'Inkscape' , 'inkscape %F' },
}
myAudioVideomenu = { 
{ 'Ncmpcpp' , 'urxvtc -e ncmpcpp' },
{ 'QT V4L2 test Utility' , 'qv4l2' },
{ 'VLC media player' , '/usr/bin/vlc %U' },
}
myOfficemenu = { 
{ 'Bitcoin' , '/usr/bin/bitcoin-qt' },
{ 'Gnumeric' , 'gnumeric %U' },
{ 'New Database' , 'libreoffice --base %U' },
{ 'New Spreadsheet' , 'libreoffice --calc %U' },
{ 'New Drawing' , 'libreoffice --draw %U' },
{ 'New Presentation' , 'libreoffice --impress %U' },
{ 'New Formula' , 'libreoffice --math %U' },
{ 'LibreOffice' , 'libreoffice %U' },
{ 'New Document' , 'libreoffice --writer %U' },
{ 'Zathura' , 'zathura' },
{ 'Zathura' , 'zathura %f' },
{ 'Zathura' , 'zathura %f' },
{ 'Zathura' , 'zathura %f' },
}
myUtilitymenu = { 
{ '7-Zip FM' , '7zFM' },
{ 'Avant Window Navigator' , 'avant-window-navigator' },
{ 'compton' , 'compton' },
{ 'Redshift' , 'gtk-redshift' },
{ 'Vi IMproved' , 'gvim -f %F' },
{ 'KeePassX' , 'keepassx %f' },
{ 'Synapse' , 'synapse' },
}
myDevelopmentmenu = { 
{ 'Qt4 Assistant ' , 'assistant-qt4' },
{ 'CMake' , 'cmake-gui %f' },
{ 'Qt4 Designer' , 'designer-qt4' },
{ 'Eclipse' , 'eclipse' },
{ 'Emacs' , 'emacs %F' },
{ 'FLUID' , 'fluid %F' },
{ 'OpenJDK Monitoring & Management Console' , '/usr/bin/jconsole' },
{ 'Qt4 Linguist ' , 'linguist-qt4' },
{ 'LÖVE' , '/usr/bin/love' },
{ 'Mplab IDE' , 'wine /home/nicolas/.wine/drive_c/Program Files (x86)/Microchip/MPLAB IDE/Core/MPLAB.exe' },
{ 'OpenJDK Policy Tool' , '/usr/bin/policytool' },
{ 'Qt4 QDbusViewer ' , 'qdbusviewer-qt4' },
{ 'Scilab advanced CLI' , 'urxvtc -e scilab-adv-cli' },
{ 'Scilab CLI' , 'urxvtc -e scilab-cli' },
{ 'Scinotes' , 'scinotes' },
{ 'GNU Octave' , 'urxvtc -e /usr/bin/octave' },
{ 'Xcos' , 'xcos' },
}
myNetworkmenu = { 
{ 'Avahi SSH Server Browser' , '/usr/bin/bssh' },
{ 'Avahi VNC Server Browser' , '/usr/bin/bvnc' },
{ 'Chromium' , 'chromium %U' },
{ 'Dropbox' , 'dropboxd' },
{ 'ELinks' , '/usr/bin/elinks %u' },
{ 'Firefox' , '/usr/lib/firefox/firefox %u' },
{ 'IcedTea Web Start' , '/usr/lib/jvm/java-7-openjdk/bin/javaws %f' },
{ 'Luakit' , 'luakit %u' },
{ 'Friends' , 'steam steam://open/friends' },
{ 'Zenmap' , 'zenmap %F' },
{ 'Zenmap (as root)' , '/usr/share/zenmap/su-to-zenmap.sh %F' },
}
mySystemmenu = { 
{ 'Avahi Zeroconf Browser' , '/usr/bin/avahi-discover' },
{ 'Cairo-Dock (no OpenGL)' , 'cairo-dock -A' },
{ 'GLX-Dock (Cairo-Dock with OpenGL)' , 'cairo-dock' },
{ 'dconf Editor' , 'dconf-editor' },
{ 'GParted' , '/usr/bin/gparted_polkit %f' },
{ 'Htop' , 'urxvtc -e htop' },
{ 'TrueCrypt' , 'truecrypt' },
{ 'urxvt (client)' , 'urxvtc' },
{ 'urxvt' , 'urxvt' },
{ 'urxvt (tabbed)' , 'urxvt-tabbed' },
{ 'UXTerm' , 'uxterm' },
{ 'Oracle VM VirtualBox' , 'VirtualBox %U' },
{ 'Wireshark' , 'wireshark %f' },
{ 'XTerm' , 'xterm' },
}
mySettingsmenu = { 
{ 'ARandR' , 'arandr' },
{ 'Awn Settings' , 'awn-settings' },
{ 'Manage Printing' , '/usr/bin/xdg-open http://localhost:631/' },
{ 'Adobe Flash Player' , 'flash-player-properties' },
{ 'IcedTea-Web Control Panel' , '/usr/lib/jvm/java-7-openjdk/bin/itweb-settings' },
{ 'Customize Look and Feel' , 'lxappearance' },
{ 'NVIDIA X Server Settings' , '/usr/bin/nvidia-settings' },
{ 'Qt4 Config ' , 'qtconfig-qt4' },
}
categoriesMenu = { 
{ 'Settings' , mySettingsmenu },
{ 'System' , mySystemmenu },
{ 'Network' , myNetworkmenu },
{ 'Development' , myDevelopmentmenu },
{ 'Utility' , myUtilitymenu },
{ 'Office' , myOfficemenu },
{ 'AudioVideo' , myAudioVideomenu },
{ 'Graphics' , myGraphicsmenu },
{ 'Game' , myGamemenu },
{ 'Others' , myOthersmenu },
{ 'Actualiser', 'lua /home/nicolas/.config/awesome/lib/menuMaker.lua'},
 }
